"""Generate compose/cameras.generated.yml from sim/cameras.yaml.

Pipeline: load (YAML) -> validate (pydantic + clip existence) -> render (pure) -> write.

    uv run python sim/gen_compose.py [--config PATH] [--out PATH] [--clips-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import difflib
import sys
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    ValidationError,
    field_validator,
    model_validator,
)

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = REPO / "sim" / "cameras.yaml"
DEFAULT_OUT = REPO / "compose" / "cameras.generated.yml"
DEFAULT_CLIPS_DIR = REPO / "media"

HEADER = "# GENERATED by sim/gen_compose.py from sim/cameras.yaml — DO NOT EDIT\n"
# Host side is relative to the compose project directory (the repo root, where the first -f
# file lives); compose resolves relative paths of every merged file against it.
CLIPS_VOLUME = "./media:/clips:ro"
RTSP_BASE = "rtsp://mediamtx:8554"
SUB_SUFFIX = "-sub"
# Installed in sim/camera/Dockerfile (fonts-dejavu-core).
OSD_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

Role = Literal["gate", "quay", "yard", "waterway"]
Preset = Literal[
    "ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"
]
Transport = Literal["tcp", "udp"]


class ConfigError(Exception):
    """Invalid camera config; the message names the offending camera id."""


def _even(v: int | None) -> int | None:
    # yuv420p subsamples chroma 2x2, so odd dimensions can't be encoded.
    if v is not None and v % 2:
        raise ValueError(f"must be even, got {v}")
    return v


class SubStream(BaseModel):
    """Sub stream settings; every field optional so a camera can override only some.

    Missing fields come from `defaults.sub`; `gop` defaults to 2 x fps.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    width: int | None = Field(default=None, gt=0)
    height: int | None = Field(default=None, gt=0)
    fps: int | None = Field(default=None, ge=1, le=60)
    bitrate: str | None = Field(default=None, pattern=r"^\d+(\.\d+)?[kM]$")
    gop: int | None = Field(default=None, ge=1)

    _even_dims = field_validator("width", "height")(_even)


@dataclass(slots=True, frozen=True)
class ResolvedSub:
    width: int
    height: int
    fps: int
    bitrate: str
    gop: int


class Defaults(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    image: str
    build: str | None = None
    preset: Preset = "veryfast"
    transport: Transport = "tcp"
    osd: StrictBool = True
    sub: SubStream | None = None


class Camera(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str = Field(pattern=r"^cam-[a-z0-9-]+$")
    role: Role
    clip: str
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    fps: int = Field(ge=1, le=60)
    bitrate: str = Field(pattern=r"^\d+(\.\d+)?[kM]$")
    gop: int = Field(ge=1)
    # Per-camera overrides of `defaults`.
    image: str | None = None
    build: str | None = None
    preset: Preset | None = None
    transport: Transport | None = None
    osd: StrictBool | None = None
    # Absent: use defaults.sub. Mapping: override some fields. null: no sub stream.
    sub: SubStream | None = None

    _even_dims = field_validator("width", "height")(_even)


class Fleet(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    version: Literal[2]
    defaults: Defaults
    cameras: list[Camera] = Field(min_length=1)

    @model_validator(mode="after")
    def _unique_ids(self) -> Fleet:
        seen: set[str] = set()
        for cam in self.cameras:
            if cam.id in seen:
                raise ValueError(f"{cam.id}: duplicate camera id")
            seen.add(cam.id)
        return self

    @model_validator(mode="after")
    def _valid_subs(self) -> Fleet:
        for cam in self.cameras:
            sub = resolve_sub(cam, self.defaults)
            if sub is None:
                continue
            # The sub stream is derived from the same frames: it can only be smaller and slower.
            if sub.width > cam.width or sub.height > cam.height:
                raise ValueError(
                    f"{cam.id}: sub {sub.width}x{sub.height} larger than main "
                    f"{cam.width}x{cam.height}"
                )
            if sub.fps > cam.fps:
                raise ValueError(f"{cam.id}: sub fps {sub.fps} higher than main fps {cam.fps}")
        return self


def resolve_sub(cam: Camera, defaults: Defaults) -> ResolvedSub | None:
    """Merge camera `sub` over `defaults.sub`; None means the camera has no sub stream."""
    if "sub" in cam.model_fields_set and cam.sub is None:
        return None
    base = defaults.sub.model_dump(exclude_none=True) if defaults.sub else {}
    over = cam.sub.model_dump(exclude_none=True) if cam.sub else {}
    merged = base | over
    if not merged:
        return None
    missing = [f for f in ("width", "height", "fps", "bitrate") if f not in merged]
    if missing:
        raise ValueError(f"{cam.id}: sub is missing {', '.join(missing)}")
    merged.setdefault("gop", 2 * merged["fps"])
    return ResolvedSub(**merged)


def _camera_label(raw: Any, index: int) -> str:
    try:
        return str(raw["cameras"][index]["id"])
    except (KeyError, IndexError, TypeError):
        return f"cameras[{index}]"


def parse(raw: Any) -> Fleet:
    """Validate a loaded YAML document; errors are prefixed with the camera id."""
    try:
        return Fleet.model_validate(raw)
    except ValidationError as e:
        lines = []
        for err in e.errors():
            loc = err["loc"]
            if len(loc) >= 2 and loc[0] == "cameras" and isinstance(loc[1], int):
                where = " ".join([_camera_label(raw, loc[1]), *map(str, loc[2:])])
            else:
                where = ".".join(map(str, loc)) or "config"
            lines.append(f"{where}: {err['msg']}")
        raise ConfigError("\n".join(lines)) from None


def load(path: Path) -> Fleet:
    with path.open(encoding="utf-8") as f:
        return parse(yaml.safe_load(f))


def check_clips(fleet: Fleet, clips_dir: Path) -> None:
    missing = [
        f"{cam.id}: clip {clips_dir / cam.clip} does not exist"
        for cam in fleet.cameras
        if not (clips_dir / cam.clip).is_file()
    ]
    if missing:
        raise ConfigError("\n".join(missing))


def warnings_for(fleet: Fleet) -> list[str]:
    out = []
    for cam in fleet.cameras:
        if cam.gop != 2 * cam.fps:
            out.append(
                f"{cam.id}: gop {cam.gop} != 2 x fps ({2 * cam.fps}); convention is a 2 s GOP"
            )
        sub = resolve_sub(cam, fleet.defaults)
        if sub and sub.gop != 2 * sub.fps:
            out.append(
                f"{cam.id}: sub gop {sub.gop} != 2 x fps ({2 * sub.fps}); convention is a 2 s GOP"
            )
    return out


def double_bitrate(bitrate: str) -> str:
    """'2M' -> '4M', '1.5M' -> '3M', '750k' -> '1500k' (unit kept)."""
    value, unit = Decimal(bitrate[:-1]), bitrate[-1]
    return f"{format((value * 2).normalize(), 'f')}{unit}"


def osd_filters(cam_id: str, height: int) -> list[str]:
    """Camera-style OSD: UTC wall clock top-left, camera id bottom-right.

    The clock is drawtext's %{gmtime} expansion, evaluated per frame as it is filtered; with -re
    and -tune zerolatency that is within a frame of the moment the frame leaves the "camera".
    Quoting: '...' hides the text from the filtergraph and option parsers; inside it, `\\:` is
    drawtext's separator between function name and argument. %T (= %H:%M:%S) avoids more colons.
    """
    size = max(12, height // 24)
    common = f"fontfile={OSD_FONT}:fontsize={size}:fontcolor=white:box=1:boxcolor=black@0.5"
    return [
        f"drawtext={common}:x=8:y=8:text='%{{gmtime\\:%Y-%m-%d %T}} UTC'",
        f"drawtext={common}:x=w-tw-8:y=h-th-8:text='{cam_id}'",
    ]


def branch(fps: int, width: int, height: int, cam_id: str, osd: bool) -> str:
    filters = [f"fps={fps}", f"scale={width}:{height}", "format=yuv420p"]
    if osd:
        filters += osd_filters(cam_id, height)
    return ",".join(filters)


def filter_graph(cam: Camera, sub: ResolvedSub | None, osd: bool) -> str:
    """One decode, then one branch per encoder (like a camera's ISP feeding two encoders)."""
    main = branch(cam.fps, cam.width, cam.height, cam.id, osd)
    if sub is None:
        return f"[0:v]{main}[main]"
    sub_chain = branch(sub.fps, sub.width, sub.height, cam.id, osd)
    return f"[0:v]split=2[m][s];[m]{main}[main];[s]{sub_chain}[sub]"


def encoder_output(
    label: str, bitrate: str, gop: int, preset: str, transport: str, url: str
) -> list[str]:
    g = str(gop)
    # fmt: off
    return [
        "-map", f"[{label}]",
        "-c:v", "libx264", "-preset", preset, "-tune", "zerolatency", "-profile:v", "main",
        "-bf", "0",
        "-b:v", bitrate, "-maxrate", bitrate, "-bufsize", double_bitrate(bitrate),
        "-g", g, "-keyint_min", g, "-sc_threshold", "0",
        "-f", "rtsp", "-rtsp_transport", transport, url,
    ]
    # fmt: on


def ffmpeg_command(cam: Camera, defaults: Defaults) -> list[str]:
    preset = cam.preset or defaults.preset
    transport = cam.transport or defaults.transport
    osd = defaults.osd if cam.osd is None else cam.osd
    sub = resolve_sub(cam, defaults)
    url = f"{RTSP_BASE}/{cam.id}"
    # fmt: off
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "warning",
        "-re", "-stream_loop", "-1", "-i", f"/clips/{cam.clip}",
        "-filter_complex", filter_graph(cam, sub, osd),
    ]
    # fmt: on
    cmd += encoder_output("main", cam.bitrate, cam.gop, preset, transport, url)
    if sub is not None:
        cmd += encoder_output("sub", sub.bitrate, sub.gop, preset, transport, url + SUB_SUFFIX)
    return cmd


def render(fleet: Fleet) -> dict[str, Any]:
    """Pure: Fleet -> compose document. Service order = YAML camera order."""
    services: dict[str, Any] = {}
    for cam in fleet.cameras:
        svc: dict[str, Any] = {"image": cam.image or fleet.defaults.image}
        build = cam.build or fleet.defaults.build
        if build:
            svc["build"] = build
        svc |= {
            # publish.sh (the image entrypoint) supervises this command: restart + SIGTERM.
            "command": ffmpeg_command(cam, fleet.defaults),
            "environment": {"CAM_NAME": cam.id},
            "volumes": [CLIPS_VOLUME],
            "depends_on": ["mediamtx"],
            "init": True,
            "restart": "unless-stopped",
            "labels": {"port.sim.role": cam.role, "port.sim.camera": cam.id},
        }
        services[cam.id] = svc
    return {"services": services}


def dump(doc: dict[str, Any]) -> str:
    return HEADER + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--clips-dir", type=Path, default=DEFAULT_CLIPS_DIR)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out is out of date")
    args = ap.parse_args(argv)

    try:
        fleet = load(args.config)
        check_clips(fleet, args.clips_dir)
    except ConfigError as e:
        print(f"gen_compose: invalid {args.config}:\n{e}", file=sys.stderr)
        return 2
    for w in warnings_for(fleet):
        print(f"gen_compose: warning: {w}", file=sys.stderr)

    text = dump(render(fleet))
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current == text:
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile=f"{args.out} (committed)",
            tofile=f"{args.out} (generated)",
        )
        sys.stderr.writelines(diff)
        print(f"gen_compose: {args.out} is out of date; run sim/gen_compose.py", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"gen_compose: wrote {args.out} ({len(fleet.cameras)} cameras)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
