"""Generate compose/cameras.generated.yml from sim/cameras.yaml.

Pipeline: load (YAML) -> validate (pydantic + clip existence) -> render (pure) -> write.

    uv run python sim/gen_compose.py [--config PATH] [--out PATH] [--clips-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import difflib
import sys
from decimal import Decimal
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = REPO / "sim" / "cameras.yaml"
DEFAULT_OUT = REPO / "compose" / "cameras.generated.yml"
DEFAULT_CLIPS_DIR = REPO / "media"

HEADER = "# GENERATED by sim/gen_compose.py from sim/cameras.yaml — DO NOT EDIT\n"
# Host side is relative to the compose project directory (the repo root, where the first -f
# file lives); compose resolves relative paths of every merged file against it.
CLIPS_VOLUME = "./media:/clips:ro"
RTSP_BASE = "rtsp://mediamtx:8554"

Role = Literal["gate", "quay", "yard", "waterway"]
Preset = Literal[
    "ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"
]
Transport = Literal["tcp", "udp"]


class ConfigError(Exception):
    """Invalid camera config; the message names the offending camera id."""


class Defaults(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    image: str
    build: str | None = None
    preset: Preset = "veryfast"
    transport: Transport = "tcp"


class Camera(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str = Field(pattern=r"^cam-[a-z0-9-]+$")
    role: Role
    clip: str
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    fps: int = Field(ge=1, le=60)
    bitrate: str = Field(pattern=r"^\d+(\.\d+)?[kM]$")
    gop: int = Field(ge=1)
    # Per-camera overrides of `defaults`.
    image: str | None = None
    build: str | None = None
    preset: Preset | None = None
    transport: Transport | None = None

    @field_validator("width", "height")
    @classmethod
    def _even(cls, v: int) -> int:
        # yuv420p subsamples chroma 2x2, so odd dimensions can't be encoded.
        if v % 2:
            raise ValueError(f"must be even, got {v}")
        return v


class Fleet(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    version: Literal[1]
    defaults: Defaults
    cameras: list[Camera] = Field(min_length=1)

    @model_validator(mode="after")
    def _unique_ids(self) -> Fleet:
        seen: set[str] = set()
        for cam in self.cameras:
            if cam.id in seen:
                raise ValueError(f"{cam.id}: duplicate camera id")
            seen.add(cam.id)
        return self


def _camera_label(raw: Any, index: int) -> str:
    try:
        return str(raw["cameras"][index]["id"])
    except (KeyError, IndexError, TypeError):
        return f"cameras[{index}]"


def parse(raw: Any) -> Fleet:
    """Validate a loaded YAML document; errors are prefixed with the camera id."""
    try:
        return Fleet.model_validate(raw)
    except ValidationError as e:
        lines = []
        for err in e.errors():
            loc = err["loc"]
            if len(loc) >= 2 and loc[0] == "cameras" and isinstance(loc[1], int):
                where = " ".join([_camera_label(raw, loc[1]), *map(str, loc[2:])])
            else:
                where = ".".join(map(str, loc)) or "config"
            lines.append(f"{where}: {err['msg']}")
        raise ConfigError("\n".join(lines)) from None


def load(path: Path) -> Fleet:
    with path.open(encoding="utf-8") as f:
        return parse(yaml.safe_load(f))


def check_clips(fleet: Fleet, clips_dir: Path) -> None:
    missing = [
        f"{cam.id}: clip {clips_dir / cam.clip} does not exist"
        for cam in fleet.cameras
        if not (clips_dir / cam.clip).is_file()
    ]
    if missing:
        raise ConfigError("\n".join(missing))


def warnings_for(fleet: Fleet) -> list[str]:
    return [
        f"{cam.id}: gop {cam.gop} != 2 x fps ({2 * cam.fps}); convention is a 2 s GOP"
        for cam in fleet.cameras
        if cam.gop != 2 * cam.fps
    ]


def double_bitrate(bitrate: str) -> str:
    """'2M' -> '4M', '1.5M' -> '3M', '750k' -> '1500k' (unit kept)."""
    value, unit = Decimal(bitrate[:-1]), bitrate[-1]
    return f"{format((value * 2).normalize(), 'f')}{unit}"


def ffmpeg_command(cam: Camera, defaults: Defaults) -> list[str]:
    preset = cam.preset or defaults.preset
    transport = cam.transport or defaults.transport
    g = str(cam.gop)
    # fmt: off
    return [
        "ffmpeg", "-hide_banner", "-loglevel", "warning",
        "-re", "-stream_loop", "-1", "-i", f"/clips/{cam.clip}",
        "-an",
        "-vf", f"scale={cam.width}:{cam.height},fps={cam.fps},format=yuv420p",
        "-c:v", "libx264", "-preset", preset, "-tune", "zerolatency", "-profile:v", "main",
        "-bf", "0",
        "-b:v", cam.bitrate, "-maxrate", cam.bitrate, "-bufsize", double_bitrate(cam.bitrate),
        "-g", g, "-keyint_min", g, "-sc_threshold", "0",
        "-f", "rtsp", "-rtsp_transport", transport, f"{RTSP_BASE}/{cam.id}",
    ]
    # fmt: on


def render(fleet: Fleet) -> dict[str, Any]:
    """Pure: Fleet -> compose document. Service order = YAML camera order."""
    services: dict[str, Any] = {}
    for cam in fleet.cameras:
        svc: dict[str, Any] = {"image": cam.image or fleet.defaults.image}
        build = cam.build or fleet.defaults.build
        if build:
            svc["build"] = build
        svc |= {
            # publish.sh (the image entrypoint) supervises this command: restart + SIGTERM.
            "command": ffmpeg_command(cam, fleet.defaults),
            "environment": {"CAM_NAME": cam.id},
            "volumes": [CLIPS_VOLUME],
            "depends_on": ["mediamtx"],
            "init": True,
            "restart": "unless-stopped",
            "labels": {"port.sim.role": cam.role, "port.sim.camera": cam.id},
        }
        services[cam.id] = svc
    return {"services": services}


def dump(doc: dict[str, Any]) -> str:
    return HEADER + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--clips-dir", type=Path, default=DEFAULT_CLIPS_DIR)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out is out of date")
    args = ap.parse_args(argv)

    try:
        fleet = load(args.config)
        check_clips(fleet, args.clips_dir)
    except ConfigError as e:
        print(f"gen_compose: invalid {args.config}:\n{e}", file=sys.stderr)
        return 2
    for w in warnings_for(fleet):
        print(f"gen_compose: warning: {w}", file=sys.stderr)

    text = dump(render(fleet))
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current == text:
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile=f"{args.out} (committed)",
            tofile=f"{args.out} (generated)",
        )
        sys.stderr.writelines(diff)
        print(f"gen_compose: {args.out} is out of date; run sim/gen_compose.py", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"gen_compose: wrote {args.out} ({len(fleet.cameras)} cameras)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
